//
//  CurrencyType.swift
//  CurrencyConverter
//
//  Created by Kyle Morton on 8/8/22.
//

import Foundation

struct CurrencyType : Identifiable {
   
    var id: String;
    var description: String;
    
    init(id: String, description: String) {
        self.id = id;
        self.description = description;
    }
}

extension CurrencyType {
    static let data: [CurrencyType] =
    [
       CurrencyType(id: "AED", description: "United Arab Emirates Dirham"),
       CurrencyType(id: "AFN", description: "Afghan Afghani"),
       CurrencyType(id: "ALL", description: "Albanian Lek"),
       CurrencyType(id: "AMD", description: "Armenian Dram"),
       CurrencyType(id: "ANG", description: "Netherlands Antillean Guilder"),
       CurrencyType(id: "AOA", description: "Angolan Kwanza"),
       CurrencyType(id: "ARS", description: "Argentine Peso"),
       CurrencyType(id: "AUD", description: "Australian Dollar"),
       CurrencyType(id: "AWG", description: "Aruban Florin"),
       CurrencyType(id: "AZN", description: "Azerbaijani Manat"),
       CurrencyType(id: "BAM", description: "Bosnia-Herzegovina Convertible Mark"),
       CurrencyType(id: "BBD", description: "Barbadian Dollar"),
       CurrencyType(id: "BDT", description: "Bangladeshi Taka"),
       CurrencyType(id: "BGN", description: "Bulgarian Lev"),
       CurrencyType(id: "BHD", description: "Bahraini Dinar"),
       CurrencyType(id: "BIF", description: "Burundian Franc"),
       CurrencyType(id: "BMD", description: "Bermudan Dollar"),
       CurrencyType(id: "BND", description: "Brunei Dollar"),
       CurrencyType(id: "BOB", description: "Bolivian Boliviano"),
       CurrencyType(id: "BRL", description: "Brazilian Real"),
       CurrencyType(id: "BSD", description: "Bahamian Dollar"),
       CurrencyType(id: "BTC", description: "Bitcoin"),
       CurrencyType(id: "BTN", description: "Bhutanese Ngultrum"),
       CurrencyType(id: "BWP", description: "Botswanan Pula"),
       CurrencyType(id: "BYN", description: "New Belarusian Ruble"),
       CurrencyType(id: "BYR", description: "Belarusian Ruble"),
       CurrencyType(id: "BZD", description: "Belize Dollar"),
       CurrencyType(id: "CAD", description: "Canadian Dollar"),
       CurrencyType(id: "CDF", description: "Congolese Franc"),
       CurrencyType(id: "CHF", description: "Swiss Franc"),
       CurrencyType(id: "CLF", description: "Chilean Unit of Account (UF)"),
       CurrencyType(id: "CLP", description: "Chilean Peso"),
       CurrencyType(id: "CNY", description: "Chinese Yuan"),
       CurrencyType(id: "COP", description: "Colombian Peso"),
       CurrencyType(id: "CRC", description: "Costa Rican Coln"),
       CurrencyType(id: "CUC", description: "Cuban Convertible Peso"),
       CurrencyType(id: "CUP", description: "Cuban Peso"),
       CurrencyType(id: "CVE", description: "Cape Verdean Escudo"),
       CurrencyType(id: "CZK", description: "Czech Republic Koruna"),
       CurrencyType(id: "DJF", description: "Djiboutian Franc"),
       CurrencyType(id: "DKK", description: "Danish Krone"),
       CurrencyType(id: "DOP", description: "Dominican Peso"),
       CurrencyType(id: "DZD", description: "Algerian Dinar"),
       CurrencyType(id: "EGP", description: "Egyptian Pound"),
       CurrencyType(id: "ERN", description: "Eritrean Nakfa"),
       CurrencyType(id: "ETB", description: "Ethiopian Birr"),
       CurrencyType(id: "EUR", description: "Euro"),
       CurrencyType(id: "FJD", description: "Fijian Dollar"),
       CurrencyType(id: "FKP", description: "Falkland Islands Pound"),
       CurrencyType(id: "GBP", description: "British Pound Sterling"),
       CurrencyType(id: "GEL", description: "Georgian Lari"),
       CurrencyType(id: "GGP", description: "Guernsey Pound"),
       CurrencyType(id: "GHS", description: "Ghanaian Cedi"),
       CurrencyType(id: "GIP", description: "Gibraltar Pound"),
       CurrencyType(id: "GMD", description: "Gambian Dalasi"),
       CurrencyType(id: "GNF", description: "Guinean Franc"),
       CurrencyType(id: "GTQ", description: "Guatemalan Quetzal"),
       CurrencyType(id: "GYD", description: "Guyanaese Dollar"),
       CurrencyType(id: "HKD", description: "Hong Kong Dollar"),
       CurrencyType(id: "HNL", description: "Honduran Lempira"),
       CurrencyType(id: "HRK", description: "Croatian Kuna"),
       CurrencyType(id: "HTG", description: "Haitian Gourde"),
       CurrencyType(id: "HUF", description: "Hungarian Forint"),
       CurrencyType(id: "IDR", description: "Indonesian Rupiah"),
       CurrencyType(id: "ILS", description: "Israeli New Sheqel"),
       CurrencyType(id: "IMP", description: "Manx pound"),
       CurrencyType(id: "INR", description: "Indian Rupee"),
       CurrencyType(id: "IQD", description: "Iraqi Dinar"),
       CurrencyType(id: "IRR", description: "Iranian Rial"),
       CurrencyType(id: "ISK", description: "Icelandic Krna"),
       CurrencyType(id: "JEP", description: "Jersey Pound"),
       CurrencyType(id: "JMD", description: "Jamaican Dollar"),
       CurrencyType(id: "JOD", description: "Jordanian Dinar"),
       CurrencyType(id: "JPY", description: "Japanese Yen"),
       CurrencyType(id: "KES", description: "Kenyan Shilling"),
       CurrencyType(id: "KGS", description: "Kyrgystani Som"),
       CurrencyType(id: "KHR", description: "Cambodian Riel"),
       CurrencyType(id: "KMF", description: "Comorian Franc"),
       CurrencyType(id: "KPW", description: "North Korean Won"),
       CurrencyType(id: "KRW", description: "South Korean Won"),
       CurrencyType(id: "KWD", description: "Kuwaiti Dinar"),
       CurrencyType(id: "KYD", description: "Cayman Islands Dollar"),
       CurrencyType(id: "KZT", description: "Kazakhstani Tenge"),
       CurrencyType(id: "LAK", description: "Laotian Kip"),
       CurrencyType(id: "LBP", description: "Lebanese Pound"),
       CurrencyType(id: "LKR", description: "Sri Lankan Rupee"),
       CurrencyType(id: "LRD", description: "Liberian Dollar"),
       CurrencyType(id: "LSL", description: "Lesotho Loti"),
       CurrencyType(id: "LTL", description: "Lithuanian Litas"),
       CurrencyType(id: "LVL", description: "Latvian Lats"),
       CurrencyType(id: "LYD", description: "Libyan Dinar"),
       CurrencyType(id: "MAD", description: "Moroccan Dirham"),
       CurrencyType(id: "MDL", description: "Moldovan Leu"),
       CurrencyType(id: "MGA", description: "Malagasy Ariary"),
       CurrencyType(id: "MKD", description: "Macedonian Denar"),
       CurrencyType(id: "MMK", description: "Myanma Kyat"),
       CurrencyType(id: "MNT", description: "Mongolian Tugrik"),
       CurrencyType(id: "MOP", description: "Macanese Pataca"),
       CurrencyType(id: "MRO", description: "Mauritanian Ouguiya"),
       CurrencyType(id: "MUR", description: "Mauritian Rupee"),
       CurrencyType(id: "MVR", description: "Maldivian Rufiyaa"),
       CurrencyType(id: "MWK", description: "Malawian Kwacha"),
       CurrencyType(id: "MXN", description: "Mexican Peso"),
       CurrencyType(id: "MYR", description: "Malaysian Ringgit"),
       CurrencyType(id: "MZN", description: "Mozambican Metical"),
       CurrencyType(id: "NAD", description: "Namibian Dollar"),
       CurrencyType(id: "NGN", description: "Nigerian Naira"),
       CurrencyType(id: "NIO", description: "Nicaraguan Crdoba"),
       CurrencyType(id: "NOK", description: "Norwegian Krone"),
       CurrencyType(id: "NPR", description: "Nepalese Rupee"),
       CurrencyType(id: "NZD", description: "New Zealand Dollar"),
       CurrencyType(id: "OMR", description: "Omani Rial"),
       CurrencyType(id: "PAB", description: "Panamanian Balboa"),
       CurrencyType(id: "PEN", description: "Peruvian Nuevo Sol"),
       CurrencyType(id: "PGK", description: "Papua New Guinean Kina"),
       CurrencyType(id: "PHP", description: "Philippine Peso"),
       CurrencyType(id: "PKR", description: "Pakistani Rupee"),
       CurrencyType(id: "PLN", description: "Polish Zloty"),
       CurrencyType(id: "PYG", description: "Paraguayan Guarani"),
       CurrencyType(id: "QAR", description: "Qatari Rial"),
       CurrencyType(id: "RON", description: "Romanian Leu"),
       CurrencyType(id: "RSD", description: "Serbian Dinar"),
       CurrencyType(id: "RUB", description: "Russian Ruble"),
       CurrencyType(id: "RWF", description: "Rwandan Franc"),
       CurrencyType(id: "SAR", description: "Saudi Riyal"),
       CurrencyType(id: "SBD", description: "Solomon Islands Dollar"),
       CurrencyType(id: "SCR", description: "Seychellois Rupee"),
       CurrencyType(id: "SDG", description: "Sudanese Pound"),
       CurrencyType(id: "SEK", description: "Swedish Krona"),
       CurrencyType(id: "SGD", description: "Singapore Dollar"),
       CurrencyType(id: "SHP", description: "Saint Helena Pound"),
       CurrencyType(id: "SLL", description: "Sierra Leonean Leone"),
       CurrencyType(id: "SOS", description: "Somali Shilling"),
       CurrencyType(id: "SRD", description: "Surinamese Dollar"),
       CurrencyType(id: "STD", description: "So Tom and Prncipe Dobra"),
       CurrencyType(id: "SVC", description: "Salvadoran Coln"),
       CurrencyType(id: "SYP", description: "Syrian Pound"),
       CurrencyType(id: "SZL", description: "Swazi Lilangeni"),
       CurrencyType(id: "THB", description: "Thai Baht"),
       CurrencyType(id: "TJS", description: "Tajikistani Somoni"),
       CurrencyType(id: "TMT", description: "Turkmenistani Manat"),
       CurrencyType(id: "TND", description: "Tunisian Dinar"),
       CurrencyType(id: "TOP", description: "Tongan Pabbanga"),
       CurrencyType(id: "TRY", description: "Turkish Lira"),
       CurrencyType(id: "TTD", description: "Trinidad and Tobago Dollar"),
       CurrencyType(id: "TWD", description: "New Taiwan Dollar"),
       CurrencyType(id: "TZS", description: "Tanzanian Shilling"),
       CurrencyType(id: "UAH", description: "Ukrainian Hryvnia"),
       CurrencyType(id: "UGX", description: "Ugandan Shilling"),
       CurrencyType(id: "USD", description: "United States Dollar"),
       CurrencyType(id: "UYU", description: "Uruguayan Peso"),
       CurrencyType(id: "UZS", description: "Uzbekistan Som"),
       CurrencyType(id: "VEF", description: "Venezuelan Bolvar Fuerte"),
       CurrencyType(id: "VND", description: "Vietnamese Dong"),
       CurrencyType(id: "VUV", description: "Vanuatu Vatu"),
       CurrencyType(id: "WST", description: "Samoan Tala"),
       CurrencyType(id: "XAF", description: "CFA Franc BEAC"),
       CurrencyType(id: "XAG", description: "Silver (troy ounce)"),
       CurrencyType(id: "XAU", description: "Gold (troy ounce)"),
       CurrencyType(id: "XCD", description: "East Caribbean Dollar"),
       CurrencyType(id: "XDR", description: "Special Drawing Rights"),
       CurrencyType(id: "XOF", description: "CFA Franc BCEAO"),
       CurrencyType(id: "XPF", description: "CFP Franc"),
       CurrencyType(id: "YER", description: "Yemeni Rial"),
       CurrencyType(id: "ZAR", description: "South African Rand"),
       CurrencyType(id: "ZMK", description: "Zambian Kwacha (pre-2013)"),
       CurrencyType(id: "ZMW", description: "Zambian Kwacha"),
       CurrencyType(id: "ZWL", description: "Zimbabwean Dollar")
    ];
}
